### ISSUE TITLE
Consider disabling CPU quota via Kubelet flag --cpu-cfs-quota=false

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#1026]
To mitigate the CPU throttling problem (https://github.com/kubernetes/kubernetes/issues/51135), we should consider disabling CPU quota/throttling all together. That's what @vishh from Google recommends.

**Comment by szuecs** [comment]
@hjacobs we have no countermeasure for overload and therefore I have to honestly disagree with the provided solution.
The question is if we disable it, what do we measure to decide if it is a success or not?

**Comment by hjacobs** [comment]
Looks like we might get https://github.com/kubernetes/kubernetes/pull/63437 merged upstream (thus changing this issue to "configure cfs quota period") :smile:

**Comment by mikkeloscar** [comment]
FYI: I back ported the patch to Kubernetes v1.9.7 and built a hyperkube image for testing.

```
registry.opensource.zalan.do/teapot/hyperkube:v1.9.7-cpu.cfs_period-flag_custom.pr-1-21
```

**Comment by hjacobs** [comment]
@mikkeloscar thanks! I actually want to see the impact/behaviour of completely disabling CPU quota, see #1044 --- e.g. it would be interesting whether the cluster's average CPU utilization increases (even in cases where limits are not reached).

**Comment by szuecs** [comment]
The problem with disabling limits is that pods that do not need much resources (requests a few) but use much will be equally treated as pods that requests resources as much as they need.

**Comment by hjacobs** [comment]
Option to disable CFS quota per cluster was rolled out in https://github.com/zalando-incubator/kubernetes-on-aws/pull/1350

**Comment by hjacobs** [comment]
We disabled CFS quota for all Zalando Kubernetes clusters and have only positive results so far.

**Comment by geraldstanje** [comment]
@hjacobs hi, is that still a thing with kubernetes with the following version?
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by szuecs** [comment]
@geraldstanje It's not a Kubernetes issue, but it shows up in Kubernetes.
There were two issues in the Kernel and as far as I know they are all fixed in new Kernel >=5.3. Maybe already backported.

**Comment by geraldstanje** [comment]
@szuecs it it still recommended to disable CFS quota in kubernetes 1.15.6?

**Comment by szuecs** [comment]
@geraldstanje we did not have the time yet to re-evaluate the change. There was a talk at the last kubecon as far as I remember, which showed that it works with the kernel bug fixes applied.
It also depends on your needs, if you want to enable it or not.

**Comment by mikkeloscar** [comment]
This is the talk @szuecs is referring to: https://www.youtube.com/watch?v=UE7QX98-kO0

**Comment by sharkymcdongles** [comment]
When quota is set to false does this mean we should not set request and limit or just set request?

**Comment by hjacobs** [comment]
@sharkymcdongles setting requests/limits also affects the QoS class, you can set requests == limits for both CPU and memory to get the highest QoS class, see also https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/ and https://www.youtube.com/watch?v=eBChCFD9hfs

**Comment by stozinho** [comment]
@hjacobs I think my question essentially the same as @sharkymcdongles ... I understand QoS within Kubes, but if we disable CFS CPU Quota, does that mean in this case I can only specify CPU Requests?

Or should we disable cpu-cfs-quota but set CPU requests == limits? (in addition to memory requests == limits so we don't over-commit memory)
And if we do set CPU limits how are they enforced if CFS quota is disabled?

**Comment by szuecs** [comment]
@stozinho it depends on the Kubernetes version as far as I remember. In older versions QoS classes relied on all requests settings are equal to the limits. I think this was fixed last year (maybe 1.18-1.20 ?). 
CPU limits are not enforced if you do not run with CFS and also with CFS you are maybe more stable CPU wise in your cluster, but you will see latency issues for workloads.
We decided to disable CFS and we also did not tested to enable it again. We might want to check it out again, but I also do not see so much value in our case.

**Comment by stozinho** [comment]
thanks @szuecs . All i am wondering, though, is if CFS is disabled, then there is no point setting a CPU limits value, as nothing will enforce it? 
Looking at Zalando kubernetes-on-aws it appears you still specify CPU limit value, even though CFS is disabled. I am just trying to understand that, essentially (is there anything enforcing that cpu limit?) 

Essentially I just want to know what to put in my manifests - requests for cpu and mem; limits just for mem?

**Comment by szuecs** [comment]
Yes enforcement is not done if you disable CFS, but the kernel default scheduler is also some kind of fair and good enough in our case.
We use requests=limits for all resource requests, because in the past the QoS decision were made on all resource types have to be set request equal limit https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed. As far as I remember it was changed to only memory, but the docs look different and state that for `Guaranteed` you need to set CPU/memory requests=limits.
The important aspect is that if you don't run in this class the oom killer will prefer to kill that process, because QoS classes configure oom_adj and oom_score_adj that are used by the oom killer to find the right process to kill in case of memory pressure.

**Comment by stozinho** [comment]
thanks @szuecs . So if you disable CFS you can still specify a CPU limit, but it doesn't have any effect.
 
yeap AFAIA you set requests = limits for mem and cpu for Guaranteed QoS. 

the comments on QoS / OOM killing for memory are interesting. So with Guaranteed mem you are less likely to be oom killed than a Burstable container.

Essentially I'm trying to unpick a lot of things and figure out a 'recommended way' for how we handle Resource Requests; whether we tweak or disable CFS entirely; how we manage our cluster addons, and how we manage tenant apps, etc.

**Comment by szuecs** [comment]
The weirdness is that it's not enough to set memory req=limit, but also CPU for getting Guaranteed class. I remember that it was changed but the docs state different, so I would keep CPU+Mem req=limit.

**Comment by stozinho** [comment]
@szuecs ahh yes I'm with you now - the scheduler wants to see that all containers in a Pod have reqs=limits, so that it will deem it to be `Guaranteed` QoS (even if in our case the CPU limit is not observed)
many thanks for all your comments! 

one last question - do you use HPA for CPU scale out, to 'protect' from the fact that there is no hard limit for CPU? (e.g. scale out horizontally if CPU rises)
