### ISSUE TITLE
Consider using the Open Policy Agent for admission control

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#1029]
Using [OPA](https://www.openpolicyagent.org/) would allow us to have flexible, dynamic admission control policies, e.g. to deny certain pod specs, white/blacklist config options etc. One existing use case is to enforce certain standard pod labels (like "application").

https://www.openpolicyagent.org/docs/kubernetes-admission-control.html

**Comment by szuecs** [comment]
We do much more with admission control, today, so likely won't happen.
