### ISSUE TITLE
attaching volumes regularly gets stuck

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#111]
error message is always the same

```
$ kubectl describe pod foo
...
  25m		1m		12	{kubelet ip-172-31-13-7.eu-central-1.compute.internal}			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "etcd-1"/"acid". list of unattached/unmounted volumes=[data]
```

observations
* ebs volume is "stuck" for days in AWS (forcing detach doesn't help)
* reboot of the corresponding instance also doesn't help
* happens on GKE as well
* several failed units show up when sshing the box
* kubelet logs show corresponding error messages

there are several issues reported upstream already
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue%20is%3Aopen%20%22list%20of%20unattached%22

**Comment by mikkeloscar** [comment]
@linki can you link the upstream issues here?

**Comment by linki** [comment]
need to sift through to find the most relevant. i leave this for now

https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue%20is%3Aopen%20%22list%20of%20unattached%22

**Comment by hjacobs** [comment]
We'll close this issue here as we are tracking it in our internal issue tracker and it's not directly related to cluster creation/updating.
