### ISSUE TITLE
S3 GetObject permission for ZMON

### ISSUE THREAD

**Issue by mohabusama** [zalando-incubator/kubernetes-on-aws#1184]
ZMON users on Kubernetes clusters cannot read S3 objects due to missing access right for ZMON role. Understandably this is for security reason.

Is it possible to get access to ``.ConfigItems`` in the Senza def as a mean to specify the exact S3 resources with proper ``GetObject`` access from ZMON workers on Kubernetes clusters?

**Comment by szuecs** [comment]
Is this fixed?

**Comment by szuecs** [comment]
I think it is
