### ISSUE TITLE
Network policies: protect pods from being accessed by all other pod in the cluster

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#119]
ensure that pods cannot connect to other pods in the cluster that they are not allowed to connect to, e.g. when running multiple patronis in the cluster.

this is not directly cluster lifecycle related but more how you configure the network policies inside. but we may have to run something in the cluster (e.g. calico node agent).

if we don't care b/c of `autobahn` then we should write it down here.

**Comment by hjacobs** [comment]
What is this about?

**Comment by linki** [comment]
Was about using NetworkPolicies to firewall Pods/Namespaces: https://kubernetes.io/docs/concepts/services-networking/network-policies/

Closing as not required for now.
