### ISSUE TITLE
prevent users from execing into arbitrary pods

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#120]
ensure that users can not exec into containers that they are not allowed to exec into.

this is not directly cluster lifecycle related but more how you configure the access policies inside. but we may have to run something in the cluster, implement the functionality in our webhook or configure our api server to not allow certain routes (there are flags for it).

if we don't care b/c of `autobahn` then we should write it down here.

**Comment by hjacobs** [comment]
What is this about?

**Comment by mikkeloscar** [comment]
Closing since we already disallow exec in production.
