### ISSUE TITLE
prevent users from modifying arbitrary pods

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#121]
ensure that users can not modify deployments that they are not allowed to modify.

this is not directly cluster lifecycle related but more how you configure the access policies inside. but we may have to run something in the cluster or implement the functionality in our webhook.

if we don't care b/c of `autobahn` then we should write it down here.

**Comment by hjacobs** [comment]
What is this about?

**Comment by Raffo** [comment]
@hjacobs Currently any user can modify applications deployed by other users. While `autobahn` will avoid this in production, it might make sense to use namespaces or something else to limit the things that the users can modify.

**Comment by mikkeloscar** [comment]
Currently we define the Cluster as the trust boundary, so every user with access to the cluster is by definition allowed to modify pods.
