### ISSUE TITLE
Is image-policy-webhook available as open-source?

### ISSUE THREAD

**Issue by towolf** [zalando-incubator/kubernetes-on-aws#1268]
Salve,

I was browsing your setup because it is very interesting.

We are currently using [a plugin for the Docker engine](https://github.com/freach/docker-image-policy-plugin) to police which images can be pulled.

But we want to drop the Docker engine and go with containerd directly, requiring a new implementation.

Since your code generally has a good quality I was wondering if this is open source?
`image: registry.opensource.zalan.do/teapot/image-policy-webhook:v0.3.9`

**Comment by hjacobs** [comment]
@towolf thanks for reaching out to us! No, the code of `image-policy-webhook` is not OSS right now (it highly depends on our internal structure and policies). What are you interested in specifically? Our Image Policy Webhook code is IMHO not very interesting. We could potentially open source the main part "somewhere" if you are interested. Maybe also check out the [Open Policy Agent (OPA)](https://www.openpolicyagent.org/) for a more generic approach. OPA can be used as Kubernetes admission controller.

**Comment by towolf** [comment]
I think we can write our own webhook, but getting the API interaction right and ironing out the corner cases could perhaps be accelerated by basing off some other project.

I'm looking for a compact single-purpose webhook impl to replace this Docker plugin. 

From a cursory glance OPA looks likely "bigger" than that ...

**Comment by towolf** [comment]
So, we wrote a ValidatingAdmissionWebhook that checks `.spec.container.image` and implements our image policy. 

From my side you can close this ticket @hjacobs .

But I am wondering, when the proper ImagePolicyWebhook rejects a pod, how is that presented to the user?

For example, when a pod from a Deployment fails validation for us now, this is only visible by using `describe` on the ReplicaSet, or bty using `get events`.

Is this better with ImagePolicyWebhook?
