### ISSUE TITLE
Consistently set "application" and "version" labels for all pods

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#127]
We agreed on using `app` and `version` as labels for all pods to identify the application ID and version. We are using this for our log shipping so we should set these labels on all pods (including `kube-system` ones).

**Comment by hjacobs** [comment]
@sarnowski mentioned to me that we should avoid abbreviations, i.e. something like `application_id` or `application_name`. I kind of agree, we just went with `app`/`version` because this looks like common labels in the Kubernetes world :smirk:

**Comment by linki** [comment]
it's also good practice to namespace your labels, e.g. we currently use

    metadata:
      annotations:
        k8s.zalando.org/dnsname: my-nginx.hackweek.zalan.do

annotations to define a custom dns name

https://github.com/zalando-incubator/kubernetes-on-aws/blob/master/docs/user-guide/tls-termination.rst#customizing-the-dns-name

**Comment by hjacobs** [comment]
@linki hmm, that's true for annotations, but I would not namespace our labels.

**Comment by linki** [comment]
@hjacobs thanks for the discussion. i agree, annotations should be namespaced, labels don't need to.

**Comment by hjacobs** [comment]
We agreed on `application`, `version` and `release` labels.

**Comment by linki** [comment]
afaik, we labeled everything. i'm going to close this if no one objects.

**Comment by hjacobs** [comment]
@linki closing.. :smirk:
