### ISSUE TITLE
Warning: No tagged subnets found; will fall-back to the current subnet only.

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#13]
```
W1020 16:30:11.032723       1 aws.go:2280] No tagged subnets found; will fall-back to the current subnet only.  This is likely to be an error in a future version of k8s.
from kube-controller-manager.yaml
```

**Comment by hjacobs** [comment]
This seems to be an issue with the ELB integration --- the ELB will only be created with the current subnet, i.e. instances in another AZ cannot be reached.

**Comment by szuecs** [comment]
All subnets (including the default subnet) of all nodes that we want to put as member into  an ELB has to be tagged to:

    # kube-aws-test-sszuecs01 is the cluster name
    KubernetesCluster: kube-aws-test-sszuecs01

**Comment by szuecs** [comment]
I tried to create 2 clusters and tagged subnets with KubernetesCluster="kube" and changed senza yaml Tags to hardcoded  KubernetesCluster="kube", but the service/LB does not work. I have no idea what happened, right now.

**Comment by hjacobs** [comment]
We "hacked" this for now in https://github.com/zalando-incubator/kubernetes-on-aws/commit/1e4035543b6a1b7d5dfffbb3818d682d69acf472 by tagging all subnets with `KubernetesCluster=kubernetes`.

**Comment by hjacobs** [comment]
Related issue in Kubernetes: https://github.com/kubernetes/kubernetes/issues/35052
