### ISSUE TITLE
Deploy kube-downscaler into production clusters

### ISSUE THREAD

**Issue by dneuhaeuser-zalando** [zalando-incubator/kubernetes-on-aws#1327]
It would be useful to have the kube-downscaler in production clusters, so that it's possible to opt-in into downscaling for:

- staging deployments into production clusters
- internal employee facing applications, that don't need to be available outside of working hours (at night, weekends)

**Comment by hjacobs** [comment]
I clearly see the benefit of having the capability in production clusters, too (e.g. for internal employee facing apps not required on weekend).
