### ISSUE TITLE
use secret to configure appdynamics agents

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#134]
follow up PR from https://github.com/zalando-incubator/kubernetes-on-aws/pull/113

* appdynamics secret should be a secret
* appdynamics account needs to be configurable

for ease of configuration it may make sense to put them all in one secret, although e.g. appdynamics account name is not necessarily a secret value.

**Comment by hjacobs** [comment]
This is no longer relevant as we are now shipping logs to Scalyr and the Cluster Lifecycle Manager supports `config_items` to support cluster specific settings like access keys.
