### ISSUE TITLE
Remove debug logging from External DNS

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#1349]
We still have "debug" logging enabled for External DNS and the comment suggests that we want to disable it as soon as we "trust" External DNS: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/external-dns/deployment.yaml#L34

I think we "trust" External DNS now, so should we change the log level?

**Comment by mikkeloscar** [comment]
Done in https://github.com/zalando-incubator/kubernetes-on-aws/commit/4942872689d1f86819c7cf2b7e0053eaee67c747#diff-51acfae938d9fe0cc68f5a4ca83a59ea
