### ISSUE TITLE
Correct cluster teardown (clean up AWS resources: ELBs, DNS, ..)

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#138]
on cluster delete we should delete resources that were created by kubernetes and friends. this can be done as part of `cluster.py delete`

what do delete
* ELBs created via services of type LoadBalander
* DNS records created via services of type LoadBalander (mate)
* EBS volumes created by Kubernetes PVs
* ... ?

or just everything?

**Comment by mikkeloscar** [comment]
related to #94

**Comment by Raffo** [comment]
@mikkeloscar suggests that we can tag every resource so that we can get rid of things.

**Comment by szuecs** [comment]
@mikkeloscar can we close this issue or do we have something left?

**Comment by mikkeloscar** [comment]
@szuecs we still need to implement proper teardown in the CLM, but we don't necessarily need to track it here.

**Comment by szuecs** [comment]
Close this, because our cluster-lifecycle-manager is not yet public
