### ISSUE TITLE
Apply DNS conntrack fix

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kubernetes-on-aws#1452]
Add randomized outgoing ports for masquerading  https://github.com/coreos/flannel/pull/1040

**Comment by hjacobs** [comment]
@szuecs can we close this? Was this applied?

**Comment by szuecs** [comment]
No https://github.com/coreos/flannel/commit/0d7b99460b81f98df43da183258edf56c4abf854 is the commit that enables fully random and latest release is 12 month ago v0.10.0 https://github.com/coreos/flannel/releases/latest but I ported a hack based on the idea of Quentin for weave which is flannel-tc https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/flannel/daemonset.yaml#L95

**Comment by szuecs** [comment]
We did coredns + dnsmasq as daemonset and bypass conntrack
