### ISSUE TITLE
Update skipper to add clusterClientRateLimit

### ISSUE THREAD

**Issue by herojan** [zalando-incubator/kubernetes-on-aws#1497]
Right now skipper only supports rate limiting per skipper node, which is not very useful and makes the rate limit responses to the clients incorrect from the point of view of an application using skipper for ingress, since it depends on which skipper instance your request hits.

[clusterClientRatelimit](https://opensource.zalando.com/skipper/reference/filters/#clusterclientratelimit) was added recently and it seems like a much better option for k8s skipper, since rate limits would be per cluster and ideally swarm mode would allow other features to be per-cluster in future too.

**Comment by szuecs** [comment]
https://github.com/zalando-incubator/kubernetes-on-aws/pull/1567 merged to dev

**Comment by szuecs** [comment]
Needs https://github.com/zalando/skipper/pull/875 and another PR here to deploy to clusters

**Comment by szuecs** [comment]
fixed deploy https://github.com/zalando-incubator/kubernetes-on-aws/pull/1613

**Comment by szuecs** [comment]
This was deployed to all clusters and enabled in test clusters.
https://github.com/zalando-incubator/kubernetes-on-aws/pull/1658 will additionally fix an issue, I found while testing the feature in a test cluster for a day.

**Comment by szuecs** [comment]
https://github.com/zalando-incubator/kubernetes-on-aws/pull/1909 will deploy a fixed version to test clusters

**Comment by szuecs** [comment]
It's available for all test clusters and opt-in via cluster registry for production clusters.

**Comment by szuecs** [comment]
This was already fixed
