### ISSUE TITLE
Remove kube-job-cleaner (?)

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#1672]
[kube-job-cleaner](https://github.com/hjacobs/kube-job-cleaner/) might be obsolete (https://github.com/hjacobs/kube-job-cleaner/issues/16) as Kubernetes 1.12 allows us to have the same feature with "TTLAfterFinished". @aermakov-zalando already created a PR to enable the new feature gate in #1668

**Comment by mikkeloscar** [comment]
Removed in https://github.com/zalando-incubator/kubernetes-on-aws/pull/2146
