### ISSUE TITLE
Update kube-state-metrics to 1.5.0+

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#1678]
There are some valuable new features, e.g. the new `kube_pod_container_status_last_terminated_reason` metric which allows us to easily track termination reasons (like `OOMKill`) as this is currently not conveniently possible (`kube_pod_container_status_terminated_reason` is only a snapshot and depending on scraping interval it would not show all reasons), see https://github.com/kubernetes/kube-state-metrics/issues/344. I saw this new metric field when I went through the Prometheus metrics (scraped from `kube-state-metrics`) with @szuecs recently.

[We currently use `kube-state-metrics` 1.3.0](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/kube-state-metrics/deployment.yaml#L27). Version 1.5.0 is currently beta, but probably available soon: https://github.com/kubernetes/kube-state-metrics/releases

**Comment by szuecs** [comment]
<s>https://github.com/zalando-incubator/kubernetes-on-aws/pull/1679</s> container is not build upstream
