### ISSUE TITLE
Kubernetes Ingress

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#169]
Using Kubernetes Ingress with Skipper and SSL termination by ALB (ELBv2):

* [kube-ingress-aws-controller](https://github.com/zalando-incubator/kube-ingress-aws-controller)
  * Deployed as deployment with replicas=1
  * Watch on Ingress resources
  * Configure one Application Load Balancer (ALB/ELBv2) per used SSL certificate
  * Attach Auto Scaling Group to ALB (using skipper NodePort)
* [skipper with Kubernetes data client](https://github.com/zalando/skipper/issues/227)
  * Deployed as DaemonSet (thus running on every node)
  * Exposes NodePort on every EC2 instance
  * Watch on Ingress resources
  * Configure routes defined by host/path matching

![kubernetes-ingress-with-skipper](https://cloud.githubusercontent.com/assets/510328/20931009/edacc630-bbcf-11e6-9aeb-8956e03e2606.png)

Advantages:

* SSL termination is done by ALB/ELB
  * No fiddling with SSL certs
  * We can use ACM
* Skipper is battle-tested as it processes all Zalando customer traffic already
* Skipper allows us to add more features in the future
  * OAuth verification
  * ...

Tasks for this cluster repo:

- [x] update [Mate](https://github.com/zalando-incubator/mate) to create DNS records for `Ingress` resources
- [x] install [kube-skipper](https://github.com/zalando/skipper/issues/227) as HTTP router
- [x] install [kube-aws-controller](https://github.com/zalando-incubator/kube-ingress-aws-controller) to create ALBs for SSL termination

**Comment by hjacobs** [comment]
First working version of Ingress/ALB manager was merged: https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/2

**Comment by Raffo** [comment]
Isn't it done? What is still pending?

**Comment by hjacobs** [comment]
@Raffo I think it's "basically" done, but we should revise all the edge/error cases (like mate crashing in some cases). I'm also not sure whether path-based routing is already implemented in Skipper or not.

**Comment by hjacobs** [comment]
@Raffo also definitely missing: HTTP support (non-SSL)!

**Comment by hjacobs** [comment]
Closing this for now, the remaining open topics are "minor" and tracked elsewhere:

* auto discovery for IAM certs https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/24
* support HTTP-only Ingress (nobody should want this! :smirk:) https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/12
