### ISSUE TITLE
Dashboard v1.5 disables petset support

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/kubernetes-on-aws#182]
We switched to 1.5 in #162 but this doesn't support PetSets (only stateful sets): https://github.com/kubernetes/dashboard/releases/tag/v1.5.0

Since we will have Kubernetes v1.4.* for hackweek, we should probably also use a compatible dashboard.

**Comment by hjacobs** [comment]
:crying_cat_face:

**Comment by hjacobs** [comment]
Will be resolved with #192

**Comment by linki** [comment]
closing as we are on 1.5.1 now.
