### ISSUE TITLE
Upgrade to Kubernetes v1.5.1

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#192]
https://github.com/kubernetes/kubernetes/releases/tag/v1.5.0

Things to consider:

* `PetSet` -> `StatefulSet`
* "anonymous authentication" (we probably want to disable this?)

**Comment by Raffo** [comment]
You wanted to say `1.5.1`, right? https://github.com/kubernetes/kubernetes/releases/tag/v1.5.1
