### ISSUE TITLE
Too many ELBs: RulesPerSecurityGroupLimitExceeded

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#195]
error thrown by kube-controller-manager:

E1213 15:56:19.248910       1 servicecontroller.go:754] Failed to process service. Retrying in 5m0s: Failed to create load balancer for service default/guy-go-example: error authorizing security group ingress: **RulesPerSecurityGroupLimitExceeded**: The maximum number of rules per security group has been reached.

**Comment by hjacobs** [comment]
Upstream issue: https://github.com/kubernetes/kubernetes/issues/26670

**Comment by mikkeloscar** [comment]
This is fixed by: https://github.com/zalando-incubator/kubernetes-on-aws/pull/390
