### ISSUE TITLE
Add "ClusterID" tag to all AWS resources

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#196]
Needed for https://github.com/zalando-incubator/kube-ingress-aws-controller

The `ClusterID` tag needs to be added to:
* all Security Groups
* all Auto Scaling Groups
* all EC2 instances
* ...

**Comment by hjacobs** [comment]
@lmineiro please add details

**Comment by hjacobs** [comment]
There was a PR adding this, but only for one resource: https://github.com/zalando-incubator/kubernetes-on-aws/pull/186

**Comment by lmineiro** [comment]
The above resources are the required ones for now

**Comment by ideahitme** [comment]
this is already implemented and deployed
