### ISSUE TITLE
Kubernetes v1.5.2 is out

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/kubernetes-on-aws#220]
https://github.com/kubernetes/kubernetes/releases/tag/v1.5.2

**Comment by hjacobs** [comment]
This looks relevant: https://github.com/kubernetes/kubernetes/pull/38375

(not relying on Docker ListImages)

**Comment by hjacobs** [comment]
@mikkeloscar PR is in the works.. :smile:
