### ISSUE TITLE
Remaining components to be OSS

### ISSUE THREAD

**Issue by anwarchk** [zalando-incubator/kubernetes-on-aws#2290]
Thanks for all the OSS contributions to the community. Just curious about this from the current README:

  * Cluster Registry to keep desired cluster states (e.g. used config channel and version)
  * Authnz Webhook to validate OAuth tokens and authorize access
 "We plan to release all required components to the community in Q2/2018."

Is there a still plan to open source the remaining components ?

**Comment by hjacobs** [comment]
Cluster Lifecycle Manager was open sourced, see https://github.com/zalando-incubator/cluster-lifecycle-manager --- the Cluster Registry and Authnz Webhook are not OSS: Cluster Registry is a simple CRUD service, Authnz Webhook is rather Zalando-specific

Thanks for pointing this out --- we should update the text!

**Comment by szuecs** [comment]
@hjacobs cluster-lifecycle-controller running in the cluster is also private, which is one part of cluster-lifecycle-manager

**Comment by szuecs** [comment]
The PR will clean this up and clarify that we are not working on releasing the mentioned components
I also updated the list of features/tools we run as infrastructure
