### ISSUE TITLE
Updating a cluster will reset ASG size

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#23]
`./cluster.py update <stack-name> <version>` will currently reset the ASG size (min, max and `DesiredCapacity`) as it updates the CF stack unconditionally.

**Comment by linki** [comment]
we may have a similar problem when we're starting to add node pools (additional ASGs) to the CF stack.

**Comment by hjacobs** [comment]
@linki adding node pools would be fine as we would not add them in the same CF stack (i.e. they will not be managed by CF or at least not within the same stack).

**Comment by linki** [comment]
having the entire cluster (including all pools) in a single CF stack *or* having different CF stacks for each set of nodes (masters, worker pool 1, worker pool 2...) is a quite fundamental design decision which we should decide in the team. /cc @mikkeloscar @Raffo @szuecs

**Comment by hjacobs** [comment]
This was fixed in #37
