### ISSUE TITLE
avoid unnecessary cross-zone traffic

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#233]
`1.5` introduced a feature where the `Service` abstraction would only forward traffic to pods on the same node.

`service.beta.kubernetes.io/external-traffic=OnlyLocal`

This could be used to avoid unnecessary cross-zone traffic, e.g. for exposed Daemon Sets.

**Comment by hjacobs** [comment]
Hmm, I checked this some time with ELB (https://github.com/kubernetes/kubernetes/issues/35187) and it did not work for me. But for Skipper node port it might make sense (?).

**Comment by hjacobs** [comment]
Closing, as we will not work on this atm:

* we use [kube-ingress-aws-controller](https://github.com/zalando-incubator/kube-ingress-aws-controller)+[skipper](https://github.com/zalando/skipper) as Ingress (see http://kubernetes-on-aws.readthedocs.io/en/latest/admin-guide/kubernetes-in-production.html#ingress): skipper calls the backend services (via `kube-proxy` iptables), the backend services do not support "local only" traffic atm
* we [implemented weighted traffic switching in Skipper](https://github.com/zalando/skipper/issues/324) which conflicts with "local traffic only" as it relies on having a fair distribution of pods and traffic
