### ISSUE TITLE
Configure default container limits/requests

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#239]
This is helpful to enforce reasonable limits/requests as not every user defines resources (we don't need to set min/max).

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/admission_control_limit_range.md

We should add a `limits.yaml` into every cluster which defines default resource requests like e.g. 200Mi memory.

**Comment by Raffo** [comment]
This is a proposal for an admission controller, is there also an implementation in kubernetes already?

**Comment by hjacobs** [comment]
Yes, it's already implemented!
