### ISSUE TITLE
Postmortem on Pending pods incident where AMI was deregistered

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#2397]
@arjunrn volunteered to do a small write-up for it :smile: 

Folder: https://github.com/zalando-incubator/kubernetes-on-aws/tree/dev/docs/postmortems

**Comment by szuecs** [comment]
Arjun is not working here anymore and this is a long time ago, so I don't remember the details.
Let's close it and do the next time better :)
