### ISSUE TITLE
Updating a cluster causes downtime for worker nodes

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#24]
Updating the cluster with `./cluster.py update <stack-name> <version>` will currently lead to a downtime for worker nodes as we are not waiting for node readiness (we just wait for ASG `InService` which does not indicate whether the node is completely up and registered).

NOTE: there is no downtime for master nodes while updating as we already correctly wait/check the ELB status for the master API server.

**Comment by linki** [comment]
so we could use an `ELB` in front of a worker pool to facilitate the same?

**Comment by mikkeloscar** [comment]
@linki I'm solving this by checking the Ready status of worker nodes through the k8s API.
