### ISSUE TITLE
Disallow DaemonSet pods to run on master nodes

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#252]
After digging into it a little more:

DaemonSet pods by default are scheduled on each node in `kubectl get nodes` including masters. There are several ways how this could be avoided, all of them are not ideal:

* Taint nodes so that DaemonSet pods without any tolerations cannot be scheduled on masters.
  * Would be nice but doesn't work.
  * Doesn't help either as users can just specify to tolerate the master taint. Admission control still needed.
* Disallow DaemonSets for users entirely
  * Users should rarely really need DaemonSets.
  * Would have to be implemented autobahn or admission control.
* Remove the node from `kubectl get nodes` (similar to GKE).
  * Bad, as it would also prevent us from using DaemonSets for ourselves (kube2iam, logging-agent).

Most effective strategy for now for me is to disable DaemonSets for any deployment via autobahn. This solves the issue of users scheduling pods on master nodes with minimal amount of effort.

Alternatively, since deployment files need to be approved, we could also define that DaemonSets are not allowed and shouldn't be approved. If, for some reason, they do get approved they get deployed as usual.

Pods of any heritage can also have a `NodeName` in the spec which bypasses the scheduler entirely and places the pod on the node. This can be a master node and should also be blocked.

**Comment by hjacobs** [comment]
@szuecs and I agreed to forbid `DaemonSet` resources for "normal" users ("PowerUser" role).
