### ISSUE TITLE
Proposal for different strategy of cluster update and node draining

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#260]
Heard about a slightly different approach of orchestrating a cluster about and node draining the other day.

##

Given a five node cluster:

* We currently cordon and drain each node one by one. This can lead to a pod being evicted from an "old" node to be rescheduled on another "old" node and thus being killed more often than necessary.

Another approach would be:

* Start five new nodes, cordon all old nodes, then start draining and terminating each node one by one. This way, pods will only be evicted once as they will immediately be scheduled on the new nodes because old nodes are already cordoned.

Given the fact that our new cluster autoscaler already excludes cordoned nodes from the available pool of resources this process would simplify even further to:

* Cordon all old nodes, wait for the cluster to be at full capacity again, then start draining and terminating each old node one by one.

**Comment by mikkeloscar** [comment]
> Given the fact that our new cluster autoscaler already excludes cordoned nodes from the available pool of resources this process would simplify even further to:

Since this would be a change in the CLM I think it should be able to perform the operation independently of what autoscaler we are using. Or it could have a mode where it assumes the autoscaler and a mode where it doesn't.

**Comment by linki** [comment]
Agree, we shouldn't rely on arbitrary side-effects between components to achieve what we want.

**Comment by Raffo** [comment]
Also: wrong repo for submitting this :-)

**Comment by mikkeloscar** [comment]
We are tracking this on the CLM (internal) repository.
