### ISSUE TITLE
Test and update to Kubernetes v1.5.3

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/kubernetes-on-aws#282]
v1.5.3 is out: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v153

Nothing stands out to me in the CHANGELOG, seems like a fairly simple update in our setup,

**Comment by szuecs** [comment]
This is interesting:

> ExperimentalCriticalPodAnnotation=True flag gate is set, kubelet will ensure that pods with scheduler.alpha.kubernetes.io/critical-pod annotation will be admitted even under resource pressure, will not be evicted, and are reasonably protected from system OOMs. (#41052, @vishh)

This is important for DCs (we had issues with it, that took down one DC):

> Kubelet will no longer set hairpin mode on every interface on the machine when an error occurs in setting up hairpin for a specific interface. (#36990, @bboreham)

interesting for the webhook:

> The SubjectAccessReview API passes subresource and resource name information to the authorizer to answer authorization queries. (#40935, @liggitt)
