### ISSUE TITLE
kube2iam: install iptables rule manually on each node

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/kubernetes-on-aws#291]
Right now we configure kube2iam to install the required iptables rule for routing traffic for the meta data url: https://github.com/jtblin/kube2iam#iptables

This means that there is no rule, and thus no protection if kube2iam isn't running on the node.

This problem is often seen when setting up a new cluster where the secretary pod comes up before kube2iam and fails because it gets the worker node IAM role instead of the intended secretary role.

**Comment by hjacobs** [comment]
We could also add a "block" rule manually before even the kubelet is started and removing it (pre hook?) when kube2iam starts thus preventing any access to EC2 meta data from pods before kube2iam is there.

**Comment by hjacobs** [comment]
OK, disregard my comment: we can add the final `iptables` rule already before `kube2iam` starts.
