### ISSUE TITLE
Standardized Kube-Janitor Rules

### ISSUE THREAD

**Issue by heroldus** [zalando-incubator/kubernetes-on-aws#2930]
In general, the deployment of [_kube-janitor_](https://github.com/hjacobs/kube-janitor) into every non-production is what were looking for to clean up our deployment artifacts in pull requests (PR).
But actually the convention in the default configuration in [`rules-config.yaml`](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/kube-janitor/rules-config.yaml) are quite strange for development teams:
- `id: require-application-label`: this one is fine
- `id: temporary-cdp-namespaces` is kind of what we need, but to specific to CDP and namespace names matching `d-*`.

*What we are aiming for?*

Imagine we are developing an application named `foobar` and have two clusters `proddi` for production and `devvi` for development. Of course, the production application from the master branch will run under `foobar.proddi.org` (`namespace: foobar`).

As kind of staging system for us and others, we would provide `foobar.devvi.org` (`namespace: foobar`) deployed from the _master_-branch and long running.
But if we are working on a PR like PR 5, we would like to get temporary resources for `foobar-pr-5.devvi.org` (namespace: pr-5-foobar`). 

_Proposed solution:_ Either we are able to overwrite the default configuration for _kube-janitor_ for our cluster or introduce kind of a company-wide standard to put temporary resources into namespaces matching `pr-*`. 

If you agree, I can create a PR for this.

**Comment by hjacobs** [comment]
I would agree that a TTL rule for namespaces matching `pr-*` in test clusters makes sense. What would be your proposed TTL?

**Comment by hjacobs** [comment]
Analyzing current namespace names: most of the users call them "foo-pr-X" apparently, so we might want to change it to something like `.*-pr-\d+.*`.

**Comment by heroldus** [comment]
@hjacobs My personal preference is between 8h and 12h, but I would start with 24h, first, to not put too much pressure on the developers. I guess initially it's easier to sell a TTL of 24h to a wider audience.

**Comment by hjacobs** [comment]
> We use a week and I think that’s probably a good default because you don’t want to be too aggressive so that people opt-out entirely

So maybe a week, just to be safe?

**Comment by heroldus** [comment]
I personally find a week too long. If needed, they can easily retrigger the deployment in dev-console. Let's start with 24 hours and extend if there are complains. Or even better let them overwrite the value for their cluster.

**Comment by hjacobs** [comment]
24h as TTL for namespaces named `.*-pr-\d+.*` sounds good to me.

**Comment by heroldus** [comment]
It looks like that [JMESPath](http://jmespath.org/specification.html) does not support regex or other string manipulation functions like `split` which would allow us to express the condition. Any ideas?

**Comment by hjacobs** [comment]
I suppose `contains(name, "-pr-")` is good enough in this case?

**Comment by aermakov-zalando** [comment]
> I personally find a week too long. If needed, they can easily retrigger the deployment in dev-console.

Why? Most of these deployments are in test clusters, which run on spot and don't cost a lot. Additionally, at the moment there are just _14_ deployments matching this pattern, so the amount of money we'll save is not really that big. Why create additional toil for the developers and us (investigating where the deployment went, asking questions in support channels, learning to keep retriggering their thing every single day if they still want to test)? A week seems perfectly fine to me, and developers that want a shorter time window can use an explicit ttl.

**Comment by heroldus** [comment]
I guess the general problem is that we don't have a nice solution for convention over configuration on cluster-level (at least I'm not aware of). Otherwise we wouldn't have this discussion. 

As we are preparing several migrations to K8s, we would like to use this paradigm to deploy PRs. We are willing to promote it as company-wide best practice. It's not only about saving money, but also it's probably easier to trace disappeared resources after 24h than after one week.

**Comment by aermakov-zalando** [comment]
We can make it configurable per cluster, if that's what you've meant.

**Comment by heroldus** [comment]
A default of `1w` would be fine as long as we can set it to `24h` for our cluster.
