### ISSUE TITLE
Kubernetes v1.6.0

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#331]
Release candidate is now available, we should start to try it out: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v160-rc1

**Comment by szuecs** [comment]
The change is enforcing this: PSP can not be used through unsecured API endpoint

**Comment by mikkeloscar** [comment]
hint:
we need to run apiserver with `--storage-backend=etcd2` until we migrate our data to etcd3.

**Comment by cemo** [comment]
Having 1.5.x documentation in another branch would be nice at least for some time.

**Comment by hjacobs** [comment]
@cemo what do you mean? This repo only contains docs like https://kubernetes-on-aws.readthedocs.io/en/latest/admin-guide/kubernetes-in-production.html

**Comment by cemo** [comment]
there are some useful references for 1.5.x :) Like: 

https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/userdata-master.yaml

**Comment by hjacobs** [comment]
OK, that's the whole idea of this repo --- giving other Kubernetes users some hints :smile: 

But it's git, so nothing is lost, probably a simple tag "v1.5.5" is good enough?

**Comment by mikkeloscar** [comment]
@hjacobs I would go with a branch like @cemo suggest, just because it's a bit arbitrary to have a tag (treated as a *release* in github) at a point in time which happens to be before we change the configuration to v1.6.0.

**Comment by cemo** [comment]
Tags are not bad but if you need to improve 1.5.x documentation until some point, this will require additional tags. Branching seems more intuitive and easy to maintain.

**Comment by cemo** [comment]
BTW Thank you so much guys. Your guidance and experience teach me a lot. I will work for setup automation with Terraform following weeks based on your documents.

**Comment by hjacobs** [comment]
@cemo thanks! As you are using Kubernetes on AWS, please check out https://github.com/hjacobs/kubernetes-on-aws-users and fill out the form to help compile a list of orgs using K8s on AWS.

**Comment by linki** [comment]
Seems like for DaemonSet updates we to change the manifests.

```
spec:
  updateStrategy: RollingUpdate
    maxUnavailable: 1
    minReadySeconds: 0
```

see:
* https://www.mirantis.com/blog/scaling-kubernetes-daemonsets
* https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/

**Comment by mikkeloscar** [comment]
@linki I updated #336 already with these changes, and tested that it works.

Left out `maxUnavailable: 1` and ` minReadySeconds: 0` since they are the defaults.
