### ISSUE TITLE
Add support for custom Scalyr server

### ISSUE THREAD

**Issue by tuxlife** [zalando-incubator/kubernetes-on-aws#361]
See kubernetes-log-watcher issue: https://github.com/zalando-incubator/kubernetes-log-watcher/issues/35

We need this feature for the scalyr backend migration.

**Comment by linki** [comment]
@tuxlife is this done? Seems like as https://github.com/zalando-incubator/kubernetes-on-aws/issues/654 was closed.

**Comment by mikkeloscar** [comment]
This was already done when switching to eu scalyr.
