### ISSUE TITLE
Web hook: Internal Server Error on missing group

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#40]
We are already tracking this issue elsewhere, but just a reminder to update the webhook to fix the Internal Server Error when the user misses the proper authorization group.

```
Error from server: an error on the server ("Internal Server Error: \"/api\"") has prevented the request from succeeding
```

**Comment by Raffo** [comment]
Closed by https://github.bus.zalan.do/teapot/k8s-authnz-webhook/pull/20

**Comment by hjacobs** [comment]
The webhook image tag was not updated so far...

**Comment by mikkeloscar** [comment]
Image updated in #54
