### ISSUE TITLE
Update to Kubernetes v1.6.3

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/kubernetes-on-aws#403]
v1.6.3 is out: https://github.com/kubernetes/kubernetes/releases/tag/v1.6.3

**Comment by hjacobs** [comment]
Just saw it too :smile:

**Comment by hjacobs** [comment]
Hyperkube image is still missing: https://quay.io/repository/coreos/hyperkube?tab=tags

**Comment by hjacobs** [comment]
I see no relevant changes in the changelog (for us).

**Comment by hjacobs** [comment]
It's now there: https://quay.io/repository/coreos/hyperkube?tag=latest&tab=tags
