### ISSUE TITLE
Audit policy metadata-only rule should include `serviceaccounts/token` resource

### ISSUE THREAD

**Issue by liggitt** [zalando-incubator/kubernetes-on-aws#4344]
The following files reference a metadata-only audit policy in order to prevent logging request/response contents for sensitive resources:

* https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/node-pools/master-default/userdata.yaml#L843

A recent Kubernetes [bugfix](https://github.com/kubernetes/kubernetes/pull/102040) means that audit-logging of subresource requests which previously failed will now log successfully. The `serviceaccounts/token` subresource responds to `TokenRequest` API calls with a newly minted service account token.

The `serviceaccounts/token` resource should also be included in the metadata-only audit policy if credentials are not intended to appear in the audit log:

```yaml
- group: "" # core
  resources: ["secrets", "configmaps", "serviceaccounts/token"]
```

**Comment by mikkeloscar** [comment]
@liggitt Thanks a lot for letting us know about this!
