### ISSUE TITLE
kube-node-drainer and reboots

### ISSUE THREAD

**Issue by tanuck** [zalando-incubator/kubernetes-on-aws#466]
Hi,

I had a question about your `kube-node-drainer` systemd service that forms part of your worker/master userdata. I've used it as inspiration for a similar service to solve a problem with worker reboots due to os updates. However, when the workers restart and return to a `Ready` state, they remain with `SchedulingDisabled`. Is that the intended behaviour for it?

Thanks,

**Comment by mikkeloscar** [comment]
@tanuck only master nodes (`cluster/userdata-master.yaml`) should have `SchedulingDisabled` in our setup. It's configured here: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/userdata-master.yaml#L95

For the workers we don't have this flag, so they are schedulable by default.

**Comment by tanuck** [comment]
Thanks. Yes but the workers still have this service: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/userdata-worker.yaml#L111

Which would mean that when they shutdown/reboot, they are also marked as `SchedulingDisabled`, as far as i understand it?

**Comment by mikkeloscar** [comment]
Ah I see, you are right. We never restart a node, but schedule a new one, so we never had this problem.

You will probably need a systemd unit which runs after the kubelet which marks it schedulable on boot. Something like:

```
 - name: kube-node-drainer.service
   enable: true
   command: start
   runtime: true
   content: |
      [Unit]
      Description=Ensure node is marked schedulable on startup.
      Requires=kubelet.service
      After=kubelet.service
      [Service]
      Type=oneshot
      RemainAfterExit=true
      ExecStart=/bin/sh -c '/usr/bin/rkt run \
      --volume=kube,kind=host,source=/etc/kubernetes,readOnly=true \
      --mount=volume=kube,target=/etc/kubernetes \
      --net=host \
      registry.opensource.zalan.do/teapot/hyperkube:v1.6.6_coreos.0 \
        --exec=/kubectl -- \
        --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
        uncordon'

      [Install]
      WantedBy=multi-user.target
```

**Comment by tanuck** [comment]
@mikkeloscar thanks, that's the sort of thing we looked in to.
