### ISSUE TITLE
Kubernetes 1.7.4

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#533]
1.7.4 contains some notable bugfixes, e.g. in the scheduler (!), we should probably use 1.7.4 instead of 1.7.3: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#changelog-since-v173

**Comment by mikkeloscar** [comment]
Just waiting for the hyperkube image on quay.io :zzz:
