### ISSUE TITLE
OTel Collector implementation

### ISSUE THREAD

**Issue by kostz** [zalando-incubator/kubernetes-on-aws#5831]
## goal
Reduce costs by reporting system kube metrics directly to lightstep without zmon in a middle, replace metrics produced by zmon checks 10577, 7381, 19704, which is top 3 zmon consumer estimated by active timeseries produced

## acceptance criteria

- [x] add parameter to whitelist additional labels in ksm for pods and ingresses to be able to join it further in lightstep
- [x] expand `prometheus` cluster role to service account in additional namespace

**Comment by demonCoder95** [comment]
@kostz is the work on the issue done? Maybe we can close it then?

**Comment by kostz** [comment]
> @kostz is the work on the issue done? Maybe we can close it then?

yes, certainly
