### ISSUE TITLE
Integrate Spot Fleet

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#61]
We should be able to trade cost-efficiency vs. availability (depending on the application) by balancing between on-demand and spot instances in a "smart" way.

**Comment by mikkeloscar** [comment]
I would consider this done with node pools running spot instances.

**Comment by hjacobs** [comment]
@mikkeloscar it's not the same thing, but I'm OK with closing this issue. We will probably invest into smarter EC2 Spot handling in the future (without Spot Fleet).
