### ISSUE TITLE
Cleaner Scalyr logging support in latest scalyr-agent release

### ISSUE THREAD

**Issue by cyburgee** [zalando-incubator/kubernetes-on-aws#620]
The latest release of the scalyr agent (https://github.com/scalyr/scalyr-agent-2/tree/v2.0.29) has better support for the json logs that come out of docker. 

In their words:

> Support to parse log lines written as a JSON object to extract line content before sending to Scalyr. You may turn this on by setting parse_lines_as_json to true in your log configuration stanza for a particular file. This is useful when uploading raw Docker logs.

It would be awesome if the images used by the logging-agent were updated to use that version.  Also it would be nice if I could access the source for `registry.opensource.zalan.do/eagleeye/scalyr-agent` so I could help out myself.

**Comment by szuecs** [comment]
Thanks for your suggestion we will check the new version.

@mohabusama, @apfeiffer85, @fmueller  can you have a look?
Thanks!

**Comment by cyburgee** [comment]
In case losing data is a cause for concern, according to one of the support reps in an email to me:

> By default, that will extract out the "log" field from the JSON objects in the log file and upload that as the log line content.  It also adds in whatever attributes are included in the JSON object, such as the `stream` field which indicates if the message was written to stdout or stderr.

Anyways, there's no need to add that `parse_lines_as_json` to the config by default, but I thought you might want that bit of information if you're debating whether to do it or not.

**Comment by mikkeloscar** [comment]
> In case losing data is a cause for concern

What do you mean by this? Just that we would lose the surrounding json structure? This would not be a problem IMO as it just makes it simpler to create custom parses when you don't have to worry about parsing json first.

Thanks for letting us know about this!

**Comment by cyburgee** [comment]
I just meant that the description from the release notes didn't indicate that you would still collect all the fields from the json log like "stream"

**Comment by mohabusama** [comment]
Thanks @cyburgee 

Already created an issue here: https://github.com/zalando-incubator/kubernetes-log-watcher/issues/49 

@mikkeloscar @szuecs

**Comment by szuecs** [comment]
Closing, because this repository does not own this component. Please check the referenced issue https://github.com/zalando-incubator/kubernetes-log-watcher/issues/49
