### ISSUE TITLE
Enable CloudFormation Stack Termination Protection

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#624]
Both Kubernetes and etcd Cloud Formation stacks should have the Stack Termination Protection enabled by default to prevent accidental deletion by some human being. See https://aws.amazon.com/about-aws/whats-new/2017/09/aws-cloudformation-now-provides-stack-termination-protection/

**Comment by mikkeloscar** [comment]
This was done in https://github.com/zalando-incubator/cluster-lifecycle-manager!
