### ISSUE TITLE
Remove version suffix for system pods like kube-dns and kubernetes-dashboard

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#63]
Minor annoyance: only two pods have a (unnecessary) version in their name. We should remove them (or alternatively have version suffixes for all pods).

I realized this while looking at the screenshot on https://twitter.com/try_except_/status/793537061374623744

**Comment by mikkeloscar** [comment]
Removing the version will make it much easier to do upgrades of clusters because we can just apply a new version with the same name.
