### ISSUE TITLE
issue in connection between master and worker in kubernetes

### ISSUE THREAD

**Issue by chiragagr727** [zalando-incubator/kubernetes-on-aws#7530]
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
root@master:/home/ubuntu# curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg       | sudo apt-key add 
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-      key(8)).
OK
Err:6 https://packages.cloud.google.com/apt kubernetes-xenial Release 404 Not Found [IP: 142.250.183.174 443]

root@master:/home/ubuntu# sudo apt-key del A362B822F6DEDC652817EA46B53DC80D13EDEF05
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK

E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Version '1.26.5-00' for 'kubectl' was not found

**Comment by szuecs** [comment]
this message is irrelevant and was posted in other projects, too.
We have to consider this as spam.
