### ISSUE TITLE
More node labels

### ISSUE THREAD

**Issue by georghildebrand** [zalando-incubator/kubernetes-on-aws#76]
Would be good to have more node labels available for node selectors. Especially: pool-name, #cpu, memory, gpu

**Comment by linki** [comment]
there's a project out there that handles this: https://github.com/Vungle/labelgun though, the implementation is questionable but rather easy to fix. actually a very nice exercise to get aquainted with the go client libraries for aws and kubernetes. /cc @erkentus ;-)

**Comment by linki** [comment]
by default it already adds the following labels

```
AvailabilityZone
InstanceType
Name
aws:cloudformation:stack-name
aws:autoscaling:groupName
aws:cloudformation:logical-id
aws:cloudformation:stack-id
KubernetesCluster
StackName
StackVersion
```

**Comment by hjacobs** [comment]
We should also add the `profile` of the node pool (as defined in our Cluster Registry) as a label.  Possible values are "worker/default", "worker/database", "worker/gpu", "master". The "master" profile identifies the pool containing the cluster master.

**Comment by mikkeloscar** [comment]
I would consider this done. We now have the ability to put custom labels on node pools in the cluster registry and already do this.
