### ISSUE TITLE
login downtime during cluster update

### ISSUE THREAD

**Issue by georghildebrand** [zalando-incubator/kubernetes-on-aws#85]
I just realized that during update of the cluster i got an login connection time out. So it seems that the master is down while increasing the size of the cluster. This is somehow wired because new machines should be added to the cluster and not removed. 

> ./cluster.py update kube-aws-test ghildebrand1 --instance-type=c4.2xlarge --worker-nodes=20

**Comment by mikkeloscar** [comment]
It's a bug that it causes a downtime of the API-server, but it's expected that the worker nodes gets switched out. It's doing a rolling update of the worker nodes (and master).

**Comment by hjacobs** [comment]
FYI: I did not experience any downtimes during my latest cluster update..

**Comment by hjacobs** [comment]
Can we somehow verify whether this is still an issue?

**Comment by hjacobs** [comment]
Closing; this issue is outdated and we did not have similar issues recently.
