### ISSUE TITLE
Wish for longer port-forward timeout

### ISSUE THREAD

**Issue by akauppi** [zalando-incubator/kubernetes-on-aws#877]
Is there a way for a `zkubectl` user to define a longer `zkubectl port-forward` timeout than the default 5 minutes? Likely not.

The [information](https://github.com/kubernetes/kubernetes/issues/19231) I've found on this suggests providing a `--streaming-connection-idle-timeout` parameter to the "kubelet". I presume this is something that should be changed within the `kubernetes-on-aws` project?

Could we have, say, 4 hours? 

The use case is:

As a developer I want to expose a service running in Kubernetes staging, so that my front end can find it.

Workarounds would mean either running a service locally, or exposing it to the Internet via Ingress.

**Comment by akauppi** [comment]
I got this tip on company Hipchat: 

> my workaround: `while true; do http :$local_port/health; sleep 60; done`

That works, i.e. making something exercise the end point, periodically. My misunderstanding was thinking that the timeout is absolute (from the time of the starting of the command). It seems to be relative to the last use of the port.

Likely nothing `zkubectl` should do about it.

**Comment by szuecs** [comment]
@akauppi I think this is a documentation request and not part of this "configuration in the open" project. Please reopen if you disagree.
