### ISSUE TITLE
Migrate all manifests to apps/v1 (Kubernetes 1.9)

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#901]
After having rolled out #787 (Kubernetes 1.9), we should now migrate all the manifests to the GA version of Workloads API (`apps/v1`). See https://kubernetes.io/docs/reference/workloads-18-19/

**Comment by mikkeloscar** [comment]
This was already done as part of #787

**Comment by hjacobs** [comment]
There are some remaining deployments to migrate, e.g. https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/ingress-template-controller/deployment.yaml#L1

```
$ rg apps/v1beta
cluster/manifests/ingress-template-controller/deployment.yaml
1:apiVersion: apps/v1beta2

cluster/manifests/kube-cluster-autoscaler/buffer-pods-deployment.yaml
1:apiVersion: apps/v1beta2

cluster/manifests/pdb-controller/deployment.yaml
1:apiVersion: apps/v1beta1

cluster/manifests/emergency-access-service/deployment.yaml
2:apiVersion: apps/v1beta1

**Comment by szuecs** [comment]
this was done
