### ISSUE TITLE
Where is cluster lifecycle manager?

### ISSUE THREAD

**Issue by imduffy15** [zalando-incubator/kubernetes-on-aws#914]
This project contains a lot of information and is really great for getting a good idea of how Zalando runs kubernetes and the rational for doing it in that manner.

The knowledge sharing here is great, but the ability to repurpose this is difficult without the cluster lifecycle manager component being opensourced.

**Comment by hjacobs** [comment]
@mikkeloscar will do a talk on the next KubeCon: [Continuously Deliver your Kubernetes Infrastructure](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2018/program/schedule/), so we hope to open source the required components before the talk :smile:

**Comment by imduffy15** [comment]
That is fantastic news @hjacobs

**Comment by mikkeloscar** [comment]
Here it is: https://github.com/zalando-incubator/cluster-lifecycle-manager :D

**Comment by hjacobs** [comment]
Mikkel's KubeCon talk about our Cluster Lifecycle management is now online: https://youtu.be/1xHmCrd8Qn8
