### ISSUE TITLE
Mate: cleanup DNS records

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#95]
Mate also needs to remove DNS records (we only add/update right now).

Idea: flag "mate-managed" DNS records with an additional `TXT` record.

**Comment by mikkeloscar** [comment]
@aryszka mentioned it was possible to add a comment to the CNAME entries, which would be a better solution.

**Comment by ideahitme** [comment]
@aryszka any idea how to achieve this via go client?

**Comment by aryszka** [comment]
@mikkeloscar @ideahitme true, what i saw is a comment field for the changebatch objects, not the record set itself. So it seems the TXT record is the best thing for this now.

**Comment by hjacobs** [comment]
Closing this issue here as we are already tracking it in our internal "mate" repo.
